### ISSUE TITLE
Mapa mental 

### ISSUE THREAD

**Issue by MarleneRamirez0731** [SistemasTecTlaxiaco/actividad-4-mapa-mental-MarleneRamirez0731#1]
Marlene Maricela Osorio Ramírez
Comunicación oral y escrita 
![Uploading png_20221003_104536_0000.png…]()

**Comment by MarleneRamirez0731** [comment]
![Uploading png_20221003_104536_0000.png…]()

**Comment by MarleneRamirez0731** [comment]
![png_20221003_104536_0000](https://user-images.githubusercontent.com/112357070/193668970-1be2fad5-7a55-437b-90e6-2460bb463dfd.png)

**Comment by AmeliReyesHernandez** [comment]
18.7 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
